version: '3.6'

services:
  app:
    image: learningtdd:latest
    ports:
      - 8081:8081
    volumes:
      - ./:/home/titor/Documents/go/src/github.com/snow-dev/learning_tdd
      - api:/usr/src/app/
    restart: on-failure
    depends_on:
      - db-postgres
    networks:
      - learningtdd

  db-postgres:
    image: postgres:latest
    container_name: learningtdd_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '9001:9001'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - learningtdd

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    depends_on:
#      - db-postgres
#    ports:
#      - "5050:5050"
#    networks:
#      - superblog
#    restart: unless-stopped

volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.

# Networks to be created to facilitate communication between containers
networks:
  learningtdd:
    driver: bridge
